### ISSUE TITLE
Scan Video option returns error

### ISSUE THREAD

**Issue by Ascirpaceus** [bw4sz/OpenCV_HummingbirdsMotion#28]
I'm analyzing video footage of birds visiting their nest using a gopro hero camera, which records in 60 fps.
When I try to set up the scan video (frames) option, I get the error:

"Traceback (most recent call last):
  File "<string>", line 112, in worker
  File "MotionMeerkat\motionClass.py", line 825, in wrap
  File "MotionMeerkat\motionClass.py", line 259, in run
TypeError: range() integer end argument expected, got float."

It happens no matter the number of frames I want to skip. I have played around with changing other settings (e.g. from MOG to Acc), with no difference in response. I have tried re-downloading the program several times, but that didn't seem to happen either. If I leave the number on zero, the program works fine, only the downside is the computing times are very long.

Also, if I choose "Video" or "Both" for the Output format, I always end up with just frames and no actual video, although this doesn't bother me too much.

**Comment by bw4sz** [comment]
Hi  @Ascirpaceus,

My apologies for the slow response, github did not forward your issue request to email. Correcting that now. Let me have a look and i'll get back to you.

**Comment by bw4sz** [comment]
Solved, please redownload. Thanks for report.
