### ISSUE TITLE
CommandLine error

### ISSUE THREAD

**Issue by cagnulein** [bw4sz/OpenCV_HummingbirdsMotion#30]
If with the last version i try to start the old commandline session it gives me:

C:\Program Files (x86)\MotionMeerkat>main.exe a b
[INFO              ] [Logger      ] Record log in C:\Users\r.viola\.kivy\logs\ki
vy_16-07-26_21.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015,
20:32:19) [MSC v.1500 32 bit (Intel)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sd
l2 (img_pil, img_ffpyplayer ignored)
[INFO              ] [Text        ] Provider: sdl2
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Window      ] Provider: sdl2
[INFO              ] [GL          ] GLEW initialization succeeded
[INFO              ] [GL          ] OpenGL version <4.4.0 - Build 20.19.15.4331>

[INFO              ] [GL          ] OpenGL vendor <Intel>
[INFO              ] [GL          ] OpenGL renderer <Intel(R) HD Graphics 5500>
[INFO              ] [GL          ] OpenGL parsed version: 4, 4
[INFO              ] [GL          ] Shading version <4.40 - Build 20.19.15.4331>

[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <32>
[INFO              ] [Shader      ] fragment shader: <WARNING: 0:7: '' :  #versi
on directive missing>
[INFO              ] [Shader      ] vertex shader: <WARNING: 0:7: '' :  #version
 directive missing>
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, n
ot docked
[INFO              ] [Clipboard   ] Provider: winctypes
Welcome to MotionMeerkat!

Welcome to MotionMeerkat!

 Traceback (most recent call last):
   File "<string>", line 201, in <module>
 NameError: name 'CommandArgs' is not defined
main returned -1

I know a and b have no sense at all but it's just to go in the first condition of this "if" statement:

if __name__ == "__main__":

     #Read in system arguments if they exist
     if len(sys.argv)> 2:
          motionVid=motionClass.Motion()                
          CommandArgs.commandargs(motionVid)
          motionVid.wrap()                
     else:            
          MotionMeerkatApp().run()
          cv2.destroyAllWindows()

**Comment by bw4sz** [comment]
Thanks for the issue, i haven't had many command line users since i changed to the kivy gui. I will look tonight.

**Comment by bw4sz** [comment]
Ah ha! Very clever. Kivy is the gui app platform, it swallows up command line processing for itself, to enter a command arg you need to add an extra -- flag.

So

python main.py -- --flag1 <arg> --flag <arg> etc.

so python main.py -- --burnin 1 --scan 2

will set the motionmeerkat args burnin and scan.

thanks for finding this, i'll add it to the wiki. What else can i do to make your user experience better?
