### ISSUE TITLE
VideoWriter Fails

### ISSUE THREAD

**Issue by bw4sz** [bw4sz/OpenCV_HummingbirdsMotion#31]
The gui fails to write video frames, just writes jpegs.

**Comment by emphillips18** [comment]
Unsure how to upvote this, but have this problem as well

**Comment by bw4sz** [comment]
@emphillips18 are you using MotionMeerkat, or DeepMeerkat. See deprecation notice

http://benweinstein.weebly.com/motionmeerkat.html

**Comment by emphillips18** [comment]
I misread the "photos rather than videos" part. Thought that was for DeepMeerkat. I will let you know if I have any other problems, thanks!
